version: '3'
services:
  prs_admin:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/quasar-gaia:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
